### ISSUE TITLE
Status indicator image not working under the listview! Binding not working

### ISSUE THREAD

**Issue by Midhushan** [Midhushan/VendDemo#2]
XAML Code : 
`<Image Grid.Row="0" gif:ImageBehavior.RepeatBehavior="Forever" gif:ImageBehavior.AnimatedSource="{Binding getImage,Mode=TwoWay,UpdateSourceTrigger=PropertyChanged}"   Height="18"  Width="20"   Stretch="Fill"  Grid.Column="2"  />`

Bind : 
`private BitmapImage _getImage;

        public BitmapImage getImage
        {
            get { return _getImage; }
            set { _getImage = value;
                OnPropertyChanged();
            }
        }

getImage = new BitmapImage(new Uri("/VendDemo;component/assets/redlight.gif", UriKind.Relative));`

**Comment by Thanu-007** [comment]
Issue solved now
